---
- hosts: aws
  gather_facts: False
  remote_user: ubuntu

  tasks :
   - name: System Update
     apt:
      upgrade: yes
      update_cache: yes
     sudo: yes

   - name: update tooling
     apt:
      name: "{{ item }}"
      update_cache: true
     with_items:
       - nodejs
       - npm
       - sqlite3
       - libsqlite3-dev
     sudo: yes

   - name: Cloning application from repo
     git:
      repo: https://github.com/vineeth993/node-sqlite.git
      version: master
      dest: /home/ubuntu/node-sqlite/
     sudo: yes

   - name: Npm installs
     npm:
      name: "{{ item }}"
      path: /home/ubuntu/node-sqlite/
     with_items:
      - sqlite3
      - express
      - ejs
     sudo: yes


   - name: Run node application
     script: install.sh
     sudo: yes

